version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: spring-learning-database
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=root
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQLDB_ROOT_PASSWORD
    networks:
      spring-learning-mysql:
    volumes:
      - db:/var/lib/mysql
  spring_learning_app:
    container_name: spring-learning-app
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=$SPRING_DB_USER_NAME
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DB_USER_PASSWORD
    networks:
      spring-learning-mysql:

networks:
  spring-learning-mysql:

volumes:
  db: